language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
deploy:
  provider: heroku
  app: http4k-data-class-gen
  api_key:
    secure: uK2U247fJoHDMrwxDZIp2AOfmL722Rqoo1u/+0F/ObntsT6fOxCsq+5J4WUzQKsLzIicmYSx1vRPkqDvSRn7YPeUFcq+x7oU8wQAr0fWwKeBOxmEZlZnz+wIu7/lmyMxfNEzuXg39R2mHdXx+Fc3rsJbCk6MnZpj09q9mLRcBkRvQblPTcM5sldZ0zjyUIOU4gkOJoCPey4P1Aova1aulfCPE4C0sy6vdpUnDUxfvsafPAKUFGjLlZKd+ispEp3aoLeFyiIt6oTR5IHyg/a61PmnoUjm7jurKcyU6pFTfTVoVJ73Qu2hGu7o8wZhsG8mLnoyecwrLvwwz9gtQEIzjnOt4L5MetNhi0Gctk34YL66K3ub8IAJI4AtzzcAbQQV1qazIEKqyzrDhkIxJn+VXVLPFR4EVz7JuHOtWQjjZ6WpJVTSiLVNvzgsDTmrkHV4er6+z5M3cxssDWvc2IHwGz5MPqo2PnSpHhnNFw3wgjLG6zyk+z/51SS65jCyHjM4n4dpzuqJu2793R87YPUWp/OS4jOyNo5Y+FQ3XncnYmAjYKqhYIYj05PvAHFsnsJwyh3UlKyWgpArklRhVefiai3hjtXCDFA7E6/DO9R9wd+4+OK3SzCVF+hdzWDxGaIAMX2NaC3x3DXGPP7YlOF60pvt0nZUgijt6Ki7gDgMdOc=
